### ISSUE TITLE
Outreach

### ISSUE THREAD

**Issue by sme-JAC** [JudicialAppointmentsCommission/digital-platform#89] opened 2019-02-22 15:21 UTC
### Work Shadowing and Outreach

Q1 How did you hear about the vacancy?
- [ ] JAC Website
- [ ] Professional body website or email (eg The Law Society)
- [ ] Professional body magazine
- [ ] Judicial Office Extranet
- [ ] Twitter
- [ ] Linkedin
- [ ] Word of mouth
- [ ] I prefer not to answer this question
Other form of communication (please specify) 
<Text Box- long answer>

Q2 Work Shadowing and Outreach
Have you attended an outreach event containing a presentation on JAC selection exercises?
<radio buttons>
    Yes
    No
    I prefer not to answer this question

Did you participate in a Judicial Work Shadowing Scheme?
<radio buttons>
    Yes
    No
    I prefer not to answer this question

**Comment by ollietreend** [comment] 2019-03-05 08:49
Closing as duplicate of #106

**Closed by ollietreend** 2019-03-05 08:49 UTC
