### ISSUE TITLE
Diversity section questions

### ISSUE THREAD

**Issue by NoraJAC** [JudicialAppointmentsCommission/digital-platform#102] opened 2019-03-01 10:06 UTC
Updated and tidied wording of questions and intro text is now ready: https://docs.google.com/document/d/1sHrhkWldpi7hxKBVl_A4X9EgM7lma-Bwboqjdp8xPl0/edit

**Comment by ollietreend** [comment] 2019-03-04 17:27
Closing as duplicate of JudicialAppointmentsCommission/digital-platform#45

**Closed by ollietreend** 2019-03-04 17:27 UTC
Labels: to do
